resources:
  requests:
    memory: "64Mi"
    cpu: "500m"
  limits:
    memory: "64Mi"
    cpu: "1"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
