apiVersion: v1
kind: Service
metadata:
  name: maroto
  labels:
    app: maroto
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: maroto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maroto
  labels:
    app: maroto
spec:
  replicas: 3
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
     maxSurge: 1
  selector:
    matchLabels:
      app: maroto
  template:
    metadata:
      labels:
        app: maroto
    spec:
      containers:
      - name: website
        image: erichegt/hello-istio:0.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 1
        env:
        - name: DELAY_VALUE
          value: "6000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  #downwardAPI
